# Generated by Django 5.0.2 on 2024-03-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="room_name",
            new_name="name",
        ),
    ]
