# Generated by Django 5.0.2 on 2024-03-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_rename_room_name_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomslot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='roomslot',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
