# Generated by Django 5.0.2 on 2024-03-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
